"""empty message

Revision ID: 2f3ba7466a45
Revises: 3402b7229050
Create Date: 2014-02-13 00:25:02.647527

"""

# revision identifiers, used by Alembic.
revision = '2f3ba7466a45'
down_revision = '3402b7229050'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('person_name', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'person_name')
    ### end Alembic commands ###
