"""empty message

Revision ID: 3755a18829ce
Revises: 3402b7229050
Create Date: 2014-02-12 01:14:55.265261

"""

# revision identifiers, used by Alembic.
revision = '3755a18829ce'
down_revision = '3402b7229050'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
