"""empty message

Revision ID: 44bd21424f45
Revises: 3755a18829ce
Create Date: 2014-02-12 01:19:32.032370

"""

# revision identifiers, used by Alembic.
revision = '44bd21424f45'
down_revision = '3755a18829ce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
