"""empty message

Revision ID: 566baae26d5e
Revises: 44bd21424f45
Create Date: 2014-02-12 01:20:11.429378

"""

# revision identifiers, used by Alembic.
revision = '566baae26d5e'
down_revision = '44bd21424f45'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
